package:
  name: hut2
  version: {{ environ.get("GIT_DESCRIBE_TAG", "")[1:] }}

source:
  git_url: ..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - aqctl_hut2 = hut2.aqctl_hut2:main

requirements:
  build:
    - python >=3.5.3
    - setuptools
  run:
    - python >=3.5.3
    - artiq

test:
  imports:
    - hut2
    - hut2.aqctl_hut2

about:
  home: https://github.com/quartiq/hut2
  license: LGPL
  summary: 'Drivers for Anel HUT2 power distribution'
